### ISSUE TITLE
Update to support crystal-db v0.7.0

### ISSUE THREAD

**Issue by ejstembler** [vladfaust/migrate.cr#22]
I'm not sure if it's as easy as simply updating the `shards.yml` file:

```yaml
dependencies:
  db:
    github: crystal-lang/crystal-db
    version: ~> 0.7.0
```

**See also**:  [Error resolving db (~> 0.7.0, ~> 0.7.0, ~> 0.6.0)](https://forum.crystal-lang.org/t/error-resolving-db-0-7-0-0-7-0-0-6-0/1153)
